##############################################
# !!! Datei umbenennen !!!              ######
# secrets_copy.toml -> secrets.toml     ######
##############################################

# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
username = "mettlsi1@students.zhaw.ch"
password = "ZHJON-UBSWC-FOANQ-CQRVR"
